name = "playground415"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Playground415"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.15.0"

[[lean_lib]]
name = "Playground415"
